# Generated by Django 3.1.4 on 2021-01-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='detailText',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
