# Generated by Django 3.1.4 on 2021-01-30 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20210130_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='pageText',
            field=models.TextField(max_length=1000),
        ),
    ]
