# Generated by Django 3.1.4 on 2021-02-11 16:00

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210130_0625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='text',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
