# Generated by Django 3.1.4 on 2021-02-11 16:01

from django.db import migrations
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210211_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabs',
            name='detailText',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tabs',
            name='text',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
