# Generated by Django 3.1.4 on 2021-02-11 16:08

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210211_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedetail',
            name='pageText',
            field=wagtail.core.fields.RichTextField(),
        ),
    ]
