# Generated by Django 3.1.4 on 2021-02-11 16:06

from django.db import migrations
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210130_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutuspage',
            name='contentText',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutuspage',
            name='ourTeamText',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='introText',
            field=wagtail.core.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='routepage',
            name='contentText',
            field=wagtail.core.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='text',
            field=wagtail.core.fields.RichTextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
