# Generated by Django 3.1.4 on 2021-02-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210211_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='acFormHeader',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='acFormText',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='mrFormHeader',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='mrFormText',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='wsFormHeader',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='wsFormText',
            field=models.TextField(default=1, max_length=400),
            preserve_default=False,
        ),
    ]
