# Generated by Django 3.1.4 on 2021-02-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appforms', '0002_auto_20210211_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
        migrations.AddField(
            model_name='reviews',
            name='avatar_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
