# Generated by Django 3.1.4 on 2021-02-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('appforms', '0003_auto_20210211_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='avatar_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image'),
        ),
    ]
